---
title: "CSC3002F - Operating Systems II"
subtitle: "Scheduling Assignment"
author: "Connor Morrison (MRRCON006)"
date: today
date-format: "Do MMMM YYYY"
format: 
  pdf:
    toc: true
  
---

```{r, include=FALSE}
pkg_vec <- c("ggplot2","ggthemes","broom","kableExtra","tidyr","tidyverse","emmeans","effectsize","car","dplyr")
for (x in pkg_vec) {
  if (!requireNamespace(x, quietly = TRUE)) {
    install.packages(x, dependencies = TRUE)
  }
  library(x, character.only = TRUE)
}

```

```{r, include=FALSE}
df = read_csv("simulation_results.csv")
df$total_patrons = factor(df$total_patrons)
df$schedalg = factor(df$schedalg)
df$drink = factor(df$drink)
df$priority = factor(df$priority)
df$queue_level = factor(df$queue_level)
```



```{r}
patron_summary <- df %>%
  group_by(total_patrons, schedalg, patron) %>%
  summarise(
    total_waiting = sum(waiting_time),
    total_turnaround = sum(turnaround_time),
    num_orders = n(),
    .groups = 'drop'
  )
plot(patron_summary %>% group_by(total_patrons,schedalg))
ggplot(patron_summary,aes(x=total_waiting,fill=schedalg)) + geom_density(alpha = 0.5)
hist(patron_summary$total_waiting)

```

```{r}
ggplot(df, aes(x=schedalg, y=waiting_time, fill=schedalg)) +
  geom_boxplot() +
  facet_wrap(~total_patrons) +
  labs(title="Waiting Time Distribution by Algorithm")

# 1. Fit the model
# We use factor() for sched_alg because it's a category, not a continuous number
fit <- lm(waiting_time ~ factor(schedalg) + total_patrons + drink, data = df)

# 2. View the significance (p-values) and magnitudes (coefficients)
summary(fit)

# 3. Check for Fairness/Starvation by plotting residuals
plot(fit, which = 1)
```
```{r}
# Compare means
model_speed <- lm(waiting_time ~ schedalg*total_patrons + priority + queue_level + drink + seed, data = df)
summary(model_speed)
plot(model_speed)
Anova(lm(waiting_time ~ seed, data=df))
Anova(model_speed)
```

## Methods

## Results

## Conclusions





























